#pragma once

#define MENU_ITEM_NEW_SCENE 1
#define MENU_ITEM_OPEN_SCENE 2
#define MENU_ITEM_SAVE_SCENE 3
#define MENU_ITEM_SAVE_SCENE_AS 4
#define MENU_ITEM_SETTINGS 5
#define MENU_ITEM_QUIT 6

#define MENU_ITEM_UNDO 7
#define MENU_ITEM_REDO 8
#define MENU_ITEM_DARK_THEME 9
#define MENU_ITEM_LIGHT_THEME 10
#define MENU_ITEM_ABOUT 11
#define MENU_ITEM_DOCUMENTATION 12

#define MENU_ITEM_IMPORT_OBJ 13
#define MENU_ITEM_IMPORT_FBX 14
#define MENU_ITEM_IMPORT_STL 15
#define MENU_ITEM_IMPORT_3DS 16
#define MENU_ITEM_IMPORT_C4D 17
#define MENU_ITEM_IMPORT_MB 18

#define MENU_ITEM_EXPORT_OBJ 19
#define MENU_ITEM_EXPORT_FBX 20
#define MENU_ITEM_EXPORT_STL 21
#define MENU_ITEM_EXPORT_MP4 22
#define MENU_ITEM_EXPORT_AVI 23
#define MENU_ITEM_EXPORT_MOV 24

#define MENU_ITEM_ASSET_CREATE_FOLDER 25
#define MENU_ITEM_ASSET_CREATE_CAMERA 26
#define MENU_ITEM_ASSET_CREATE_NULL_OBJECT 27
#define MENU_ITEM_ASSET_CREATE_CUBE 28
#define MENU_ITEM_ASSET_CREATE_SPHERE 29
#define MENU_ITEM_ASSET_CREATE_CAPSULE 30
#define MENU_ITEM_ASSET_CREATE_CYLINDER 31

