name: Gource Action
on:
  push:
    branches:
      - master

jobs:
  create-gource-video:
    name: Record and save gource video
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        
      - name: 'Record user activity'
        uses: nbprojekt/gource-action@v1
        with:
          git_url: https://github.com/HighLo-Engine/HighLo-Engine
          gource_title: 'HighLo-Engine'
          gource_resolution: '1080p'
          gource_fps: 60
          gource_font_size: 40
          
      - name: 'Compress gource video'
        uses: a7ul/tar-action@v1.1.0
        id: compress
        with:
          command: c
          files: |
            ./gource/gource.mp4
          outPath: ${{ github.sha }}.tar.gz

      - name: 'Upload gource video'
        uses: actions/upload-artifact@v2
        with:
          name: Gource
          path: ${{ github.sha }}.tar.gz
          retention-days: 1
          
  upload-gource-video-to-webserver:
    name: Upload gource video to HighLo Webserver
    runs-on: ubuntu-latest
    needs: create-gource-video
    
    steps:
      - name: 'Download artifact'
        uses: actions/download-artifact@v2
        with:
          name: Gource
          
      - name: 'Upload'
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: ${{ github.sha }}.tar.gz
          target: ${{ secrets.PATH }}
          
      - name: 'Extract archive on Webserver'
        uses: appleboy/ssh-action@master
        env:
          GITHUB_SHA: ${{ github.sha }}
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          envs: GITHUB_SHA
          script: |
            tar xzf ${{ secrets.PATH }}/${GITHUB_SHA}.tar.gz -C "${{ secrets.PATH }}/gource.mp4"
            rm ${{ secrets.PATH }}/${GITHUB_SHA}.tar.gz
          
          